/// Single-value spacing scale based on 4px unit
enum Spacing {
  none,
  xs,
  sm,
  md,
  lg,
  xl,
  xxl,
  xxxl,
  huge,
  massive;

  String get css => switch (this) {
        Spacing.none => '0',
        Spacing.xs => '4px',
        Spacing.sm => '8px',
        Spacing.md => '16px',
        Spacing.lg => '24px',
        Spacing.xl => '32px',
        Spacing.xxl => '48px',
        Spacing.xxxl => '64px',
        Spacing.huge => '96px',
        Spacing.massive => '120px',
      };

  double get value => switch (this) {
        Spacing.none => 0,
        Spacing.xs => 4,
        Spacing.sm => 8,
        Spacing.md => 16,
        Spacing.lg => 24,
        Spacing.xl => 32,
        Spacing.xxl => 48,
        Spacing.xxxl => 64,
        Spacing.huge => 96,
        Spacing.massive => 120,
      };
}

/// Compound padding presets
enum PaddingPreset {
  none,
  xs,
  sm,
  md,
  lg,
  xl,
  xxl,
  xxxl,
  xsMd,
  smMd,
  mdLg,
  lgXl,
  xsSm,
  buttonSm,
  buttonMd,
  buttonLg,
  card,
  section,
  sectionY,
  heroY,
  hugeY,
  horizontalSm,
  horizontalMd,
  horizontalLg,
  verticalMd,
  verticalLg,
  topSm,
  topMd,
  topLg,
  smLg,
  mdXl,
  horizontalXl,
  bottomMd,
  badge,
  inlineCode,
  chip;

  String get css => switch (this) {
        PaddingPreset.none => '0',
        PaddingPreset.xs => '4px',
        PaddingPreset.sm => '8px',
        PaddingPreset.md => '16px',
        PaddingPreset.lg => '24px',
        PaddingPreset.xl => '32px',
        PaddingPreset.xxl => '48px',
        PaddingPreset.xxxl => '64px',
        PaddingPreset.xsMd => '4px 16px',
        PaddingPreset.smMd => '8px 16px',
        PaddingPreset.mdLg => '16px 24px',
        PaddingPreset.lgXl => '24px 32px',
        PaddingPreset.xsSm => '4px 8px',
        PaddingPreset.buttonSm => '6px 12px',
        PaddingPreset.buttonMd => '10px 16px',
        PaddingPreset.buttonLg => '12px 24px',
        PaddingPreset.card => '16px 32px',
        PaddingPreset.section => '24px 48px',
        PaddingPreset.sectionY => '80px 24px',
        PaddingPreset.heroY => '120px 24px',
        PaddingPreset.hugeY => '96px 0',
        PaddingPreset.horizontalSm => '0 8px',
        PaddingPreset.horizontalMd => '0 16px',
        PaddingPreset.horizontalLg => '0 24px',
        PaddingPreset.verticalMd => '16px 0',
        PaddingPreset.verticalLg => '24px 0',
        PaddingPreset.topSm => '8px 0 0 0',
        PaddingPreset.topMd => '16px 0 0 0',
        PaddingPreset.topLg => '24px 0 0 0',
        PaddingPreset.smLg => '8px 24px',
        PaddingPreset.mdXl => '16px 32px',
        PaddingPreset.horizontalXl => '0 32px',
        PaddingPreset.bottomMd => '0 0 16px 0',
        PaddingPreset.badge => '2px 8px',
        PaddingPreset.inlineCode => '2px 6px',
        PaddingPreset.chip => '4px 12px',
      };
}

/// Compound margin presets
enum MarginPreset {
  none,
  xs,
  sm,
  md,
  lg,
  xl,
  autoX,
  autoY,
  auto,
  topSm,
  topMd,
  topLg,
  bottomXs,
  bottomSm,
  bottomMd,
  bottomLg,
  bottomXl,
  bottomXxl,
  bottomXxxl,
  topXs,
  topXl,
  topXxl,
  verticalSm,
  verticalMd,
  verticalLg,
  verticalXl,
  horizontalSm,
  horizontalMd,
  horizontalLg,
  rightSm,
  rightMd,
  rightLg,
  leftSm,
  leftMd,
  leftLg,
  centerBottomMd,
  centerBottomLg,
  centerBottomXl,
  centerBottomXxl;

  String get css => switch (this) {
        MarginPreset.none => '0',
        MarginPreset.xs => '4px',
        MarginPreset.sm => '8px',
        MarginPreset.md => '16px',
        MarginPreset.lg => '24px',
        MarginPreset.xl => '32px',
        MarginPreset.autoX => '0 auto',
        MarginPreset.autoY => 'auto 0',
        MarginPreset.auto => 'auto',
        MarginPreset.topXs => '4px 0 0 0',
        MarginPreset.topSm => '8px 0 0 0',
        MarginPreset.topMd => '16px 0 0 0',
        MarginPreset.topLg => '24px 0 0 0',
        MarginPreset.topXl => '32px 0 0 0',
        MarginPreset.topXxl => '48px 0 0 0',
        MarginPreset.bottomXs => '0 0 4px 0',
        MarginPreset.bottomSm => '0 0 8px 0',
        MarginPreset.bottomMd => '0 0 16px 0',
        MarginPreset.bottomLg => '0 0 24px 0',
        MarginPreset.bottomXl => '0 0 32px 0',
        MarginPreset.bottomXxl => '0 0 48px 0',
        MarginPreset.bottomXxxl => '0 0 64px 0',
        MarginPreset.verticalSm => '8px 0',
        MarginPreset.verticalMd => '16px 0',
        MarginPreset.verticalLg => '24px 0',
        MarginPreset.verticalXl => '32px 0',
        MarginPreset.horizontalSm => '0 8px',
        MarginPreset.horizontalMd => '0 16px',
        MarginPreset.horizontalLg => '0 24px',
        MarginPreset.rightSm => '0 8px 0 0',
        MarginPreset.rightMd => '0 16px 0 0',
        MarginPreset.rightLg => '0 24px 0 0',
        MarginPreset.leftSm => '0 0 0 8px',
        MarginPreset.leftMd => '0 0 0 16px',
        MarginPreset.leftLg => '0 0 0 24px',
        MarginPreset.centerBottomMd => '0 auto 16px auto',
        MarginPreset.centerBottomLg => '0 auto 24px auto',
        MarginPreset.centerBottomXl => '0 auto 32px auto',
        MarginPreset.centerBottomXxl => '0 auto 48px auto',
      };
}

/// Gap presets for flex and grid layouts
enum Gap {
  none,
  xs,
  sm,
  md,
  lg,
  xl,
  xxl,
  xxxl;

  String get css => switch (this) {
        Gap.none => '0',
        Gap.xs => '4px',
        Gap.sm => '8px',
        Gap.md => '16px',
        Gap.lg => '24px',
        Gap.xl => '32px',
        Gap.xxl => '48px',
        Gap.xxxl => '64px',
      };

  double get value => switch (this) {
        Gap.none => 0,
        Gap.xs => 4,
        Gap.sm => 8,
        Gap.md => 16,
        Gap.lg => 24,
        Gap.xl => 32,
        Gap.xxl => 48,
        Gap.xxxl => 64,
      };
}
